import { NextResponse } from "next/server";

import { isWorkflowEnabled } from "@/lib/automation/gate";
import { CONTENT_GENERATION_WORKFLOW, runContentGeneration, GenerationError } from "@/lib/content/generate";
import { getServerEnv } from "@/lib/env.server";
import { logger } from "@/lib/logger";
import { SIGNATURE_HEADER, TIMESTAMP_HEADER, verifySignature } from "@/lib/webhooks/signature";

/**
 * Content generation webhook for n8n (spec §44, §47).
 *
 * The `04_news_selection_processing` trigger, which runs after a human has
 * selected three stories. Signed the same way as the discovery, ranking and
 * notification webhooks — see the discovery route for why the body is read as
 * raw text before verification.
 */
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * A run makes two AI calls per story with deliberate pacing between them to
 * stay inside the free plan's per-minute limits (§29), so it is slow by design.
 */
export const maxDuration = 300;

/** The actor recorded on versions generated by the schedule rather than a person. */
const SYSTEM_ACTOR = "n8n:04_news_selection_processing";

export async function POST(request: Request) {
  const body = await request.text();

  const verification = verifySignature({
    secret: getServerEnv().N8N_WEBHOOK_SECRET,
    signature: request.headers.get(SIGNATURE_HEADER),
    timestamp: request.headers.get(TIMESTAMP_HEADER),
    body,
  });

  if (!verification.ok) {
    // The reason goes to the log, never to the caller (§56).
    logger.warn("Rejected content generation webhook", { reason: verification.reason });

    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!(await isWorkflowEnabled(CONTENT_GENERATION_WORKFLOW))) {
    logger.info("Content generation skipped: disabled from the Automation Control Center");

    return NextResponse.json({ skipped: true, reason: "This automation is disabled." });
  }

  try {
    const outcome = await runContentGeneration(SYSTEM_ACTOR);

    return NextResponse.json(
      {
        status: outcome.status,
        // §21: the caller is told plainly whether this copy is real.
        mode: outcome.mode,
        stories: outcome.stories,
        posts: outcome.posts,
        // §52: per-platform failures are reported, not swallowed.
        problems: outcome.problems,
        detail: outcome.detail,
      },
      /*
       * A run that generated nothing answers 502 so n8n sees a failed step.
       * PARTIAL is a success with problems attached: some platforms have
       * copy waiting for review, and hiding that behind an error would be
       * as misleading as hiding the failures.
       */
      { status: outcome.status === "FAILED" ? 502 : 200 },
    );
  } catch (error) {
    if (error instanceof GenerationError) {
      // Configuration, not a transport failure: an incomplete brand profile.
      logger.warn("Content generation could not start", { reason: error.message });

      return NextResponse.json({ error: error.message }, { status: 409 });
    }

    logger.error("Content generation webhook failed", {
      error: error instanceof Error ? error.message : String(error),
    });

    return NextResponse.json({ error: "Generation failed" }, { status: 500 });
  }
}
